//
// Linux_DHCPRegisteredProfile.mof
//
// © Copyright IBM Corp. 2007
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
// 
// You can obtain a current copy of the Eclipse Public License from
// http://www.opensource.org/licenses/eclipse-1.0.php
// 
// Author:  Wolfgang Taphorn <taphorn (at) de.ibm.com>
// 
// 

[Description ("A class which is used during SLP discovery to identify"
              "that the DHCP task is available")]

class Linux_DHCPRegisteredProfile : CIM_RegisteredProfile {

};
