[Description(" Entity to represent the Hosts in the dhcp.conf file.")
]


class Linux_DHCPHost : Linux_DHCPEntity {

	};

[Description("Entity to represent a filter to indicate a change in the Host entity in the dhcpd.conf file.")
]

class Linux_DHCPHost_Ind : CIM_Indication {

};		
