[Description(" Entity to represent the Groups in the dhcp.conf file.")
]

class Linux_DHCPGroup : Linux_DHCPEntity {

	
	};
[Description("Entity to represent a filter to indicate a change in the Group entity in the dhcpd.conf file.")
]

class Linux_DHCPGroup_Ind : CIM_Indication {

};
